export * from './home'
export * from './detail'
export * from './siginIn'
export * from './register'
export * from './search'
export * from './shoppingCart'
export * from './placeOrder'
export * from './404'